### ISSUE TITLE
Welcome page for the first start. 

### ISSUE THREAD

**Issue by jaminzoda** [jaminzoda/terra-antiqua#136]
It would be good to show a welcome page for users when  starting the plugin for the first time. On the welcome page the user will be given general idea about the work of the plugin and providing a link to a manual and perhaps an example qgis project with example data.

**Comment by Diego635** [comment]
Implemented here: a06da87c81b1e88164be40fb7770a3f5395e6abe
Text successively updated here: 01fbc29f3122effb63e636c99a8edfc82b115956 here: decd238c72699993de869434d10a1091cccad3f1 and here: b67785558b99616a6d1c828163dd6cddde456178
