### ISSUE TITLE
Different  paleoshorelines after smoothing

### ISSUE THREAD

**Issue by jaminzoda** [jaminzoda/terra-antiqua#140]
Sometimes one map can be smoothed several times, for example when creating several versions of one map or when fixing a part of the map and smoothing again. This leads to different shorelines in different versions of the map, if different somoothing factor is used. To fix this problem two enhancements should be introduced in smoothing tool:
1) Smooth inside polygons - for the case when only part of the map should be smoothed multiple times;
2) Introducing an optional parameter for keeping the shorelines fixed and changing the algorithm to include this functionality - for the case when the whole should be smoothed multiple times.

**Comment by Diego635** [comment]
Solved in #220 
which adds the option to reset the Pls automatically after using the smoothing
