### ISSUE TITLE
Fill gaps with specific elevation value. 

### ISSUE THREAD

**Issue by jaminzoda** [jaminzoda/terra-antiqua#143]
The gaps in rasters are now filled by interpolation. But sometimes users need to fill them with some arbitrary values. In this case, we need an option to fill gaps with specific values. This can be done either in Modify Topography, Remove Artefacts or Standard Processing.

**Comment by Diego635** [comment]
Fixed in #221
But still need to revise the **help text for fill gaps.html** in Branch for **Release Candidate v1.1**
