### ISSUE TITLE
QGIS freezing using several tools with QGIS 3.20 3.16 and 3.10

### ISSUE THREAD

**Issue by Diego635** [jaminzoda/terra-antiqua#211]
This issue happened in a Windows 10 system running QGIS 3.20 and TA v1.0.2
Tools like isost_comp, modify_tb, or create_tb were causing QGIS to freeze. Compile_tb didn't cause the bug.
QGIS froze as soon as the user selected the tool.

More information about the version used by other users and whether they encountered bugs or not will come.

**Comment by Diego635** [comment]
This bug happened once more on Windows 10 with QGIS 3.20 but also 3.16.
The tools that caused this bug are: Set Pls, Modify TB, Create TB
The user said:

> When I use one of these three tools, QGIS freezes. The program isn't answering anymore and I have to close and reopen it. The task manager shows me, that QGIS is still using CPU and memory. I deinstalled QGIS 3.20 (with deleting appdata and registry) and installed 3.16 instead (and installed Terra Antiqua again). Problem is still the same.

**Comment by jaminzoda** [comment]
Tested on windows 10 (20H2) with qgis of 3.10, 3.16, 1.18 and 3.20 versions. TA version used was 1.0.2. Could not replicate the bug. It might be related to other plugins install for in user's qgis environment. 
@Diego635 , could you replicate this issue on your machine? If yes, what plugins have you got  installed in your qgis?
